### ISSUE TITLE
year 2016 in contents

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/ONT-HG1#6]
Is the year incorrect in https://github.com/nanoporetech/ONT-HG1/blob/master/CONTENTS.md ? Says 2016, or is this not the newest data?

**Comment by cjw85** [comment]
Thanks, that is indeed incorrect. The data was collected in May 2015 and has been recently re-basecalled following improvements to the basecaller.

**Comment by wdecoster** [comment]
Alright - thanks for clarifying!
