### ISSUE TITLE
Aligned reads to Mitochondria genome?

### ISSUE THREAD

**Issue by danarte** [nanoporetech/ONT-HG1#7]
Hello, I was wondering why there was no Mitochondria in the table with the alignments to different chromosomes.

Did you perform some kind of filtering against mito-DNA during library prep? or it was simply filtered/ignored/not-aligned-to during the alignment step?
In any case, can I obtain the reads that are aligned to the Mitochondria? (We can download the fast5 files and align them to Mito on our own, but the question is whether there are actually reads that align to Mito in the fast5 files?)

Thanks,
Artem.

**Comment by cjw85** [comment]
Hi @danarte,

To my knowledge, there was no filtering in the library prep.

The chr1-22,X,Y bams were created from the "merged" bam (also listed in the table):
https://s3-eu-west-1.amazonaws.com/ont-hg1b/alignment/merge_sort/cliveome2.bam

by a simple filter (but a filter version was not created for MT). I suspect it is the above you will want to download. Do be aware that secondary and supplementary alignments were removed.

**Comment by danarte** [comment]
So just to make sure I understand you correctly; If I download all (or some fraction) of the fast5 files, and align them to the Mitochondria genome, I should get some reads to align to that reference? 

Thanks for your quick response,
Artem.

**Comment by cjw85** [comment]
Yes (though naturally very few reads will align to the MT genome, so if you download a small random subset you will likely not find any).

**Comment by danarte** [comment]
Can you clarify on that?
Because from our experience, with regular NGS experiments (from illumina), a substantial percentage of reads will align to the Mitochondria (with a decent variation between different samples).
Is it different with nanopore data? or this is simply your observation from this dataset?

**Comment by cjw85** [comment]
If you download the full bam (and its index) I linked above, you will see there are very few reads aligned to MT.

**Comment by danarte** [comment]
Oh, I thought you excluded MT from the alignment when creating the specified bam file.
I will check it out.
Thank you very much.
