### ISSUE TITLE
Downloading fast5 files based on IDs from the merged bam ?

### ISSUE THREAD

**Issue by danarte** [nanoporetech/ONT-HG1#8]
Hello again,
I want to download some fast5 files based on reads from the merged bam.

For example, here are the first few reads from the bam:
```
70bb92ac-1ea9-42cc-b096-dabff60477a0    16      1       10001   13      3414S17M1I...
6bbae6c0-bfb5-4ab0-965d-31cb9118811c    16      1       10001   0       3908S15M1D...
667968e1-7637-4370-a1a9-bbe83dd95f13    16      1       10001   3       19S10M2I24M...
6719f8cb-ce6a-4b07-b798-4a20e419595e    16      1       10001   6       3387S9M2I13M...
```

The read identifier is the first string, and the rest of the line contains information relevant to the alignment.

But the download links for the individual fast5 files looks like this:
```
https://ont-hg1b.s3.amazonaws.com/GridION CliveOME_V2/1/gridion00_20170502_FNFAE32997_MN00002_sequencing_throughput_GridION_ONTHG1_89225_ch307_read256_strand.fast5
https://ont-hg1b.s3.amazonaws.com/GridION CliveOME_V2/1/gridion00_20170502_FNFAE33378_MN00003_mux_scan_GridION_ONTHG1_70982_ch437_read334_strand.fast5
https://ont-hg1b.s3.amazonaws.com/GridION CliveOME_V2/1/gridion00_20170502_FNFAE32997_MN00001_sequencing_throughput_GridION_ONTHG1_47141_ch384_read257_strand.fast5
https://ont-hg1b.s3.amazonaws.com/GridION CliveOME_V2/1/gridion00_20170502_FNFAE33378_MN00003_sequencing_throughput_GridION_ONTHG1_56274_ch226_read443_strand.fast5
https://ont-hg1b.s3.amazonaws.com/GridION CliveOME_V2/1/gridion00_20170504_FNFAE32772_MN00000_sequencing_throughput_GridION_ONTHG1_84529_ch346_read9795_strand.fast5
https://ont-hg1b.s3.amazonaws.com/GridION CliveOME_V2/1/gridion00_20170502_FNFAE32997_MN00001_sequencing_throughput_GridION_ONTHG1_47141_ch476_read174_strand.fast5
```

Is there any way to connect between the two? Can I select the correct fast5 download links based on the read ID from the merged bam?

Thanks.

**Comment by cjw85** [comment]
IIRC, the file:
https://s3-eu-west-1.amazonaws.com/ont-hg1b/basecalling_summary.txt.gz

listed on the contents page should provide a link between the read UUID and filename. Apologies that this wasn't clear.

**Comment by danarte** [comment]
Oh yeah, right.
I missed the fact that the all the basecalls were replaced by basecalls from guppy, I still remember the original publication where it was basecalled with albacore (if i'm not mistaken). So I ignored this file when I saw it (because it's named "Guppy basecalling_summary.txt.gz").

Anyway, this solves my issue, you can close it when/if you want.

Thanks for the very fast reply (as always).

**Comment by cjw85** [comment]
I've added a note to the contents page noting the above file.
